### ISSUE TITLE
Connector URL error

### ISSUE THREAD

**Issue by DRSchlaubi** [SignPath/github-action-submit-signing-request#4]
My build failed with: 
```
Error: SignPath signing request was not created. Please make sure that connector-url is pointing to the SignPath GitHub Actions connector endpoint.

```

The connector is set to https://githubactions.connectors.signpath.io/

Job: https://github.com/DRSchlaubi/tonbrett/actions/runs/11690496098/job/32556079133

**Comment by askmeaboutlo0m** [comment]
Also having this problem, so you're not alone.

Before noticing this ticket, I was going to wait until Austrian work hours tomorrow to see if the connector gets revived and otherwise shoot a mail to support. If you already sent them a mail, let me know, then I'll hold off on doubling up on it.

**Comment by paulsavoie** [comment]
We identified the underlying issue and will prepare a hotfix release. I'll keep you posted when it is operational again.

**Comment by paulsavoie** [comment]
Should work again, thanks for the info, see https://about.signpath.io/documentation/changelog/?component=github_connector
